name: darkgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
